# before committing check this file here: https://lint.travis-ci.org/
language: python

python:
  - 3.6
#  - 2.7  # TODO enable in the future, right now python3 version is hardcoded in the jupyter notebook file

# use ubuntu 16.04
dist: xenial

# install packages from requirement.txt and other stuff
install:
  - pip install -r requirements.txt
  - pip install nbval flake8

# finally run tests
script:
  - py.test --nbval --sanitize-with .doc_sanitize.cfg
  - py.test --nbval-lax --sanitize-with .doc_sanitize.cfg
  - flake8 .
